rango/urls.py
from django.conf.urls import url
from rango import views

app_name = "rango"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^about/$', views.about, name="about"),
    url(r'^add_category/$', views.add_category, name="add_category"),
    url(r'^add_page/(?P<category_name_slug>[\w\-]+)$', views.add_page, name="add_page"),
    url(r'^category/(?P<category_name_slug>[\w\-]+)$', views.show_category, name="show_category"),
    url(r'^restricted/$', views.restricted, name="restricted"),
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.user_login, name="login"),
    url(r'^logout/$', views.user_logout, name="logout"),
]

tango_with_django_project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name="姓名", unique=True)
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to="profile_images", blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ("name", )


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ("category", )

    def clean_url(self):
        url = self.cleaned_data.get('url')

        if url.startswith("https://"):
            self.errors['url'] = "网址不能以https开头"
        return url


class UserForm(forms.ModelForm):
    username = forms.CharField(error_messages={'required': '用户名不能为空！', 'invalid': '用户名输入错误！'})
    password = forms.CharField(widget=forms.PasswordInput(), error_messages={'required': '密码不能为空！', 'invalid': '密码输入错误!'})

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from datetime import datetime
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm


def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}
    # visitor_cookie_handler(request, response)
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context=context_dict)
    return response


def about(request):
    if request.session.test_cookie_worked():
        print("test cookie worked!")
        request.session.delete_test_cookie()
    context_dict = {'name': 'root'}
    return render(request, 'rango/about.html', context=context_dict)
    # return HttpResponse("Rango says here is the about page." + "<a href='/rango/'>index</a>")


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango/category.html', context=context_dict)


def add_category(request):
    form = CategoryForm()
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == "POST":
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'rango/register.html', {'user_form': user_form,
                                                   'profile_form': profile_form,
                                                   'registered': registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print("Invalid login details:{0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html', {})


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("rango:index"))


# def visitor_cookie_handler(request, response):
def visitor_cookie_handler(request):
    # visits = int(request.COOKIES.get('visits', '1'))
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    # last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], "%Y-%m-%d %H:%M:%S")
    if(datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        # response.set_cookie('last_visit', str(datetime.now()))
        request.session['last_visit'] = str(datetime.now())
    else:
        # response.set_cookie('last_visit', last_visit_cookie)
        request.session['last_visit'] = last_visit_cookie
    # response.set_cookie('visits', visits)
    request.session['visits'] = visits


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    about
{% endblock %}
{% block body_block %}
    <div>
        Rango says here is the about page.
        <img src="{% static 'images/rango.jpg' %}" alt="rango">
    </div>
    <h3>This tutorial has been put together by {{ name }}</h3>
    <img src="{{ MEDIA_URL }}cat.jpg" alt="cat">
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% block title_block %}
    Rango
{% endblock %}
{% block body_block %}
    <h1>Add a Category</h1>
    <div>
        <form action="{% url 'rango:add_category' %}" method="post" id="category_form">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category">
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% block title_block %}
    Rango
{% endblock %}
{% block body_block %}
    <h1>Add a page</h1>
    <div>
        <form action="{% url 'rango:add_page' category.slug%}" method="post">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                <div>
                    {{ hidden }}
                </div>
            {% endfor %}
            {% for field in form.visible_fields %}
                <div>
                    {{ field.help_text }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <input type="submit" value="add a page">
        </form>
    </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="zh-cmn-Hans">
<head>
    <meta charset="UTF-8">
    <title>Rango - {% block title_block %}How to Tango with Django!{% endblock %}</title>
</head>
<body>
<div>
    {% block sidebar_block %}
        {% get_category_list category %}
    {% endblock %}
</div>
<div>
    {% block body_block %}
        This is body_block's default content.
    {% endblock %}
</div>
<hr>
<div>
    <ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
            <li><a href="{% url 'rango:logout' %}">Logout</a></li>
            <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
        {% else %}
            <li><a href="{% url 'rango:register' %}">Register Here</a></li>
            <li><a href="{% url 'rango:login' %}">Login</a></li>
        {% endif %}
        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>
    </ul>
</div>
</body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    {{ category.name }}
{% endblock %}
{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add a page</a>
        {% endif %}
    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <li>
                    <strong>
                        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                    </strong>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/index.html
{% extends "rango/base.html" %}
{% load staticfiles %}
{% block title_block %}
    Rango
{% endblock %}
{% block body_block %}
    <h1>Rango says...</h1>
{#    <p>visits: {{ request.COOKIES.visits }}</p>#}
    <p>visits: {{ visits }}</p>
    {% if user.is_authenticated %}
        <div>
            howdy {{ user.username }}
        </div>
    {% else %}
        <div>
            hey there partner!
        </div>
    {% endif %}
    <div>
        <h3>Most Liked Categories</h3>
        {% if categories %}
            <ul>
                {% for category in categories %}
                    <li>
                        {#                    <a href="/rango/category/{{ category.slug }}">{{ category.name }}</a>#}
                        <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present.</strong> <br>
        {% endif %}
    </div>
    <div>
        <h3>Most viewed Pages</h3>
        <ul>
            {% for page in pages %}
                <li>
                    <a href="{{ page.url }}">{{ page.title }}-->{{ page.views }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango">
    </div>
{% endblock %}

templates/rango/login.html
{% extends "rango/base.html" %}
{% load staticfiles %}
{% block title_block %}
    Login
{% endblock %}
{% block body_block %}
    <h1>Login to Rango</h1>
    <form action="{% url 'rango:login' %}" method="post">
        {% csrf_token %}
        Username: <input type="text" name="username" vlaue="" size="50"> <br>
        Password: <input type="password" name="password" vlaue="" size="50"> <br>
        <input type="submit" value="submit">
    </form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Register
{% endblock %}
{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form action="{% url 'rango:register' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register" name="submit">
        </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends "rango/base.html" %}
{% block title_block %}
    Restricted
{% endblock %}
{% block body_block %}
    Since you're logged in, you can see this text!
{% endblock %}
<br>
<a href="{% url 'rango:index' %}">index</a>